"""Comprehensive dynamic systems and block diagram simulation library.
Re-exports all continuous, discrete, nonlinear, logical, matrix, lookup, source, sink, routing,
signal attribute, verification, string, user function, subsystem, and dashboard blocks.
"""

from __future__ import annotations

# Base
from .base import Block

# Continuous & State-Space
from .continuous import (
    IntegratorBlock,
    IntegratorLimitedBlock,
    SecondOrderIntegratorBlock,
    SecondOrderIntegratorLimitedBlock,
    DerivativeBlock,
    TransferFunctionBlock,
    TransferFcnBlock,
    ZeroPoleBlock,
    StateSpaceBlock,
    DescriptorStateSpaceBlock,
    TransportDelayBlock,
    VariableTimeDelayBlock,
    VariableTransportDelayBlock,
    EntityTransportDelayBlock,
    FirstOrderHoldBlock,
    PIDBlock,
    PIDControllerBlock,
    PIDController2DOFBlock,
)

# Discrete Control & Filters
from .discrete import (
    UnitDelayBlock,
    DelayBlock,
    VariableIntegerDelayBlock,
    ResettableDelayBlock,
    TappedDelayBlock,
    DifferenceBlock,
    DiscreteDerivativeBlock,
    DiscreteFIRFilterBlock,
    DiscreteFilterBlock,
    DiscreteTransferFcnBlock,
    TransferFcnFirstOrderBlock,
    TransferFcnLeadOrLagBlock,
    TransferFcnRealZeroBlock,
    TransferFcnDirectFormIIBlock,
    TransferFcnDirectFormIITimeVaryingBlock,
    DiscreteZeroPoleBlock,
    DiscreteStateSpaceBlock,
    FixedPointStateSpaceBlock,
    DiscreteTimeIntegratorBlock,
    DiscretePIDBlock,
    DiscretePIDControllerBlock,
    DiscretePIDController2DOFBlock,
    MemoryBlock,
    PropagationDelayBlock,
    ZeroOrderHoldBlock,
)

# Discontinuities & Nonlinearities
from .discontinuities import (
    SaturationBlock,
    SaturationDynamicBlock,
    RateLimiterBlock,
    RateLimiterDynamicBlock,
    DeadZoneBlock,
    DeadZoneDynamicBlock,
    BacklashBlock,
    RelayBlock,
    CoulombViscousFrictionBlock,
    QuantizerBlock,
    HitCrossingBlock,
    PWMBlock,
    VariablePulseGeneratorBlock,
    WrapToZeroBlock,
)

# Logic and Bit Operations
from .logic_bit import (
    LogicalOperatorBlock,
    RelationalOperatorBlock,
    CompareToConstantBlock,
    CompareToZeroBlock,
    IntervalTestBlock,
    IntervalTestDynamicBlock,
    BitClearBlock,
    BitSetBlock,
    BitwiseOperatorBlock,
    BitToIntegerConverterBlock,
    IntegerToBitConverterBlock,
    ExtractBitsBlock,
    FloatExtractBitsBlock,
    ShiftArithmeticBlock,
    CombinatorialLogicBlock,
    DetectChangeBlock,
    DetectIncreaseBlock,
    DetectDecreaseBlock,
    DetectRisePositiveBlock,
    DetectRiseNonnegativeBlock,
    DetectFallNegativeBlock,
    DetectFallNonpositiveBlock,
)

# Math Operations
from .math_ops import (
    GainBlock,
    SliderGainBlock,
    SumBlock,
    ProductBlock,
    DivideBlock,
    DotProductBlock,
    ProductOfElementsBlock,
    AbsBlock,
    SignBlock,
    SqrtBlock,
    BiasBlock,
    UnaryMinusBlock,
    MathFunctionBlock,
    RoundingFunctionBlock,
    TrigonometricFunctionBlock,
    SineWaveFunctionBlock,
    PolynomialBlock,
    MinMaxBlock,
    MinMaxRunningResettableBlock,
    ComplexToMagnitudeAngleBlock,
    MagnitudeAngleToComplexBlock,
    ComplexToRealImagBlock,
    RealImagToComplexBlock,
    WeightedSampleTimeMathBlock,
    IncrementRealWorldBlock,
    DecrementRealWorldBlock,
    IncrementStoredIntegerBlock,
    DecrementStoredIntegerBlock,
    DecrementToZeroBlock,
    DecrementTimeToZeroBlock,
    FindNonzeroElementsBlock,
    AlgebraicConstraintBlock,
)

# Matrix Operations
from .matrix_ops import (
    MatrixConcatenateBlock,
    VectorConcatenateBlock,
    CreateDiagonalMatrixBlock,
    ExtractDiagonalBlock,
    TransposeBlock,
    HermitianTransposeBlock,
    MatrixSquareBlock,
    IdentityMatrixBlock,
    IsHermitianBlock,
    IsSymmetricBlock,
    IsTriangularBlock,
    CrossProductBlock,
    ExpandScalarBlock,
    SubmatrixBlock,
    ReshapeBlock,
    SqueezeBlock,
    PermuteMatrixBlock,
    PermuteDimensionsBlock,
    ProductMatrixMultiplyBlock,
    ArrayProcessingSubsystemBlock,
    NeighborhoodProcessingSubsystemBlock,
    PixelProcessingSubsystemBlock,
)

# Lookup Tables
from .lookup_tables import (
    LookupTable1DBlock,
    LookupTable2DBlock,
    LookupTableNDBlock,
    DirectLookupTableNDBlock,
    LookupTableDynamicBlock,
    PrelookupBlock,
    InterpolationUsingPrelookupBlock,
    SineLookupBlock,
)

# Sources
from .sources import (
    ConstantBlock,
    EnumeratedConstantBlock,
    GroundBlock,
    StepSourceBlock,
    StepBlock,
    RampSourceBlock,
    RampBlock,
    SineSourceBlock,
    SineWaveBlock,
    ChirpSignalBlock,
    ClockBlock,
    DigitalClockBlock,
    PulseGeneratorBlock,
    BandLimitedWhiteNoiseBlock,
    RandomNumberBlock,
    UniformRandomNumberBlock,
    RepeatingSequenceBlock,
    RepeatingSequenceInterpolatedBlock,
    RepeatingSequenceStairBlock,
    CounterFreeRunningBlock,
    CounterLimitedBlock,
    SignalGeneratorBlock,
    WaveformGeneratorBlock,
    SignalEditorBlock,
    FromWorkspaceBlock,
    FromFileBlock,
    FromSpreadsheetBlock,
    PlaybackBlock,
)

# Sinks
from .sinks import (
    ScopeSinkBlock,
    ScopeBlock,
    FloatingScopeBlock,
    ScopeViewerBlock,
    DisplaySinkBlock,
    DisplayBlock,
    TerminatorBlock,
    StopSimulationBlock,
    ToWorkspaceBlock,
    ToFileBlock,
    RecordSinkBlock,
)

# Signal Routing & Data Stores
from .routing import (
    SwitchBlock,
    MultiportSwitchBlock,
    IndexVectorBlock,
    ManualSwitchBlock,
    MergeBlock,
    MuxBlock,
    DemuxBlock,
    SelectorBlock,
    BusCreatorBlock,
    BusSelectorBlock,
    BusAssignmentBlock,
    GotoBlock,
    FromBlock,
    GotoTagVisibilityBlock,
    DataStoreMemoryBlock,
    DataStoreReadBlock,
    DataStoreWriteBlock,
    StateReaderBlock,
    StateWriterBlock,
    ParameterWriterBlock,
    EnvironmentControllerBlock,
    VariantSourceBlock,
    VariantSinkBlock,
    ManualVariantSourceBlock,
    ManualVariantSinkBlock,
    VariantStartBlock,
    VariantEndBlock,
)

# Signal Attributes
from .signal_attributes import (
    ICBlock,
    DataTypeConversionBlock,
    DataTypeConversionInheritedBlock,
    DataTypeDuplicateBlock,
    DataTypePropagationBlock,
    DataTypeScalingStripBlock,
    ProbeBlock,
    WidthBlock,
    RateTransitionBlock,
    SignalConversionBlock,
    SignalSpecificationBlock,
    UnitConversionBlock,
    WeightedSampleTimeBlock,
    BusToVectorBlock,
)

# Model Verification
from .model_verification import (
    AssertionBlock,
    CheckStaticRangeBlock,
    CheckDynamicRangeBlock,
    CheckStaticGapBlock,
    CheckDynamicGapBlock,
    CheckStaticLowerBoundBlock,
    CheckStaticUpperBoundBlock,
    CheckDynamicLowerBoundBlock,
    CheckDynamicUpperBoundBlock,
    CheckDiscreteGradientBlock,
    CheckInputResolutionBlock,
)

# Strings
from .strings import (
    StringConstantBlock,
    StringCompareBlock,
    StringConcatenateBlock,
    StringContainsBlock,
    StringCountBlock,
    StringFindBlock,
    StringLengthBlock,
    SubstringBlock,
    ToStringBlock,
    StringToDoubleBlock,
    StringToSingleBlock,
    StringToEnumBlock,
    StringToASCIIBlock,
    ASCIItoStringBlock,
    ComposeStringBlock,
    ScanStringBlock,
)

# User-Defined Functions
from .user_functions import (
    FcnBlock,
    MATLABFunctionBlock,
    PythonCodeBlock,
    InterpretedMATLABFunctionBlock,
    SFunctionBlock,
    SFunctionBuilderBlock,
    CCallerBlock,
    CFunctionBlock,
    FunctionCallerBlock,
    SimulinkFunctionBlock,
    MATLABSystemBlock,
    InitializeFunctionBlock,
    ReinitializeFunctionBlock,
    ResetFunctionBlock,
    TerminateFunctionBlock,
)

# Subsystems and Hierarchy
from .ports_subsystems import (
    InportBlock,
    Inport,
    OutportBlock,
    Outport,
    InBusElementBlock,
    OutBusElementBlock,
    EnableBlock,
    TriggerBlock,
    SubsystemBlock,
    EnabledSubsystemBlock,
    TriggeredSubsystemBlock,
    EnabledAndTriggeredSubsystemBlock,
    ResettableSubsystemBlock,
    ForEachSubsystemBlock,
    ForIteratorSubsystemBlock,
    WhileIteratorSubsystemBlock,
    IfBlock,
    IfActionSubsystemBlock,
    SwitchCaseBlock,
    SwitchCaseActionSubsystemBlock,
    ModelBlock,
    ModelReferenceBlock,
    VariantSubsystemBlock,
    UnitSystemConfigurationBlock,
    FunctionCallGeneratorBlock,
    FunctionCallSubsystemBlock,
    FunctionCallSplitBlock,
    FunctionCallFeedbackLatchBlock,
    FunctionElementBlock,
    FunctionElementCallBlock,
)

# Dashboard and Custom Controls
from .dashboard import (
    SliderBlock,
    HorizontalSliderBlock,
    VerticalSliderBlock,
    KnobBlock,
    RotarySwitchBlock,
    ToggleSwitchBlock,
    RockerSwitchBlock,
    SliderSwitchBlock,
    PushButtonBlock,
    CallbackButtonBlock,
    CheckBoxBlock,
    ComboBoxBlock,
    RadioButtonBlock,
    EditBlock,
    CustomEditBoxBlock,
    GaugeBlock,
    CircularGaugeBlock,
    HalfGaugeBlock,
    LinearGaugeBlock,
    QuarterGaugeBlock,
    HorizontalGaugeBlock,
    VerticalGaugeBlock,
    LampBlock,
    MultiStateImageBlock,
    DashboardDisplayBlock,
    DashboardScopeBlock,
)

# Messages and Events
from .messages_events import (
    QueueBlock,
    SendBlock,
    ReceiveBlock,
    MessageMergeBlock,
    MessageTriggeredSubsystemBlock,
    HitSchedulerBlock,
    SequenceViewerBlock,
)

# Model Utilities
from .model_utilities import (
    DocBlock,
    ModelInfoBlock,
    BlockSupportTableBlock,
    TimedBasedLinearizationBlock,
    TriggerBasedLinearizationBlock,
)
